In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1、读取数据
path = "http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(path, names=column_name)

In [3]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [4]:
# 2、缺失值处理
# 1）替换-》np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

In [5]:
data.isnull().any() # 不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [6]:
# 3、划分数据集
from sklearn.model_selection import train_test_split

In [7]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [8]:
# 筛选特征值和目标值
x = data.iloc[:, 1: -1]
y = data["Class"]

In [9]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [11]:
x_train.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
638                4                        1                         1   
365                2                        1                         1   
439                5                        1                         1   
447                5                        1                         1   
561                5                        1                         1   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
638                  1                            2           1   
365                  1                            2           1   
439                  1                            2           1   
447                  1                            2           1   
561                  1                            2           1   

     Bland Chromatin  Normal Nucleoli  Mitoses  
638                1                1        1  
365                2                1        1  
439                1                1        1  
447                1                1        1  
561                3                1        1

In [12]:
# 4、标准化
from sklearn.preprocessing import StandardScaler

In [13]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

D:\SOFTWARE\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\SOFTWARE\Anaconda\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
D:\SOFTWARE\Anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
x_train

array([[-0.18916259, -0.71122266, -0.7579151 , ..., -0.99781927,
        -0.62504583, -0.34253346],
       [-0.87605087, -0.71122266, -0.7579151 , ..., -0.59267774,
        -0.62504583, -0.34253346],
       [ 0.15428155, -0.71122266, -0.7579151 , ..., -0.99781927,
        -0.62504583, -0.34253346],
       ...,
       [ 0.15428155,  1.58933873,  1.89543554, ...,  1.4330299 ,
        -0.62504583, -0.34253346],
       [-0.53260673, -0.71122266, -0.7579151 , ...,  1.4330299 ,
        -0.62504583, -0.34253346],
       [ 0.49772569, -0.38257104, -0.09457744, ..., -0.99781927,
        -0.62504583, -0.34253346]])

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
# 5、预估器流程
estimator = LogisticRegression()
estimator.fit(x_train, y_train)

D:\SOFTWARE\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
# 逻辑回归的模型参数：回归系数和偏置
estimator.coef_

array([[ 1.56968888,  0.33188923,  0.5213502 ,  0.49346841, -0.30246907,
         1.50055384,  1.29755857,  0.97587101,  0.85367296]])

In [18]:
estimator.intercept_

array([-0.96040695])

In [19]:
# 6）模型评估
# 直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值：\n", y_test == y_predict)

# 计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

y_predict:
 [2 2 2 2 2 4 4 4 2 2 4 2 2 4 2 4 2 2 4 4 2 4 4 4 2 4 2 2 4 2 4 2 4 2 2 2 4
 2 4 2 2 2 2 2 2 2 2 2 2 4 4 4 2 4 2 4 2 4 2 2 2 4 2 4 4 2 4 4 2 4 4 4 2 2
 2 2 2 2 4 2 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 4 2 2 2 2 4 2
 4 4 2 2 4 2 4 4 2 2 2 2 2 2 4 2 2 2 4 2 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 4 4 2 4 2 2 4 2 2 2 4 4 2 2 2 2 2 2 2 2 2]
直接比对真实值和预测值：
 490     True
307     True
509     True
48      True
115     True
173     True
582     True
196    False
564     True
577     True
99      True
553     True
461     True
85      True
394     True
254     True
354     True
382     True
46      True
205     True
694     True
25      True
633     True
231     True
497     True
56      True
390     True
567     True
20      True
660     True
       ...  
342     True
593     True
652     True
19      True
163     True
80      True
629     True
450     True
419     True
608     True
483     True
146    False
574     True
682     True
309     True
246     True
627     True
21

In [20]:
# 查看精确率、召回率、F1-score
from sklearn.metrics import classification_report

In [22]:
report = classification_report(y_test, y_predict, labels=[2, 4], target_names=["良性", "恶性"])

In [24]:
print(report)

              precision    recall  f1-score   support

          良性       0.96      0.97      0.97       115
          恶性       0.94      0.91      0.93        56

   micro avg       0.95      0.95      0.95       171
   macro avg       0.95      0.94      0.95       171
weighted avg       0.95      0.95      0.95       171



In [25]:
y_test.head()

490    2
307    2
509    2
48     2
115    2
Name: Class, dtype: int64

In [26]:
# y_true：每个样本的真实类别，必须为0（反例），1（正例）标记
# 将y_test 转换成 0 1
y_true = np.where(y_test > 3, 1, 0)

In [27]:
y_true

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
from sklearn.metrics import roc_auc_score

In [29]:
roc_auc_score(y_true, y_predict)

0.9423136645962733